### ISSUE TITLE
Clarification before contributing

### ISSUE THREAD

**Issue by patcon** [djoos-cookbooks/xdebug#1]
Hey David,

Couple questions:
1) I notice the cookbook isn't yet functional. I don't suppose you have local changes you're waiting to push?
2) Any objection to using an attribute namespace like `default['php']['xdebug']['blah']` since it's a pear package? I like that you host it as a separate cookbook instead of as a php recipe like mod_xdebug (the approach others are using), but it would be nice to use the same namespace -- easier to mix and match between this cookbook and others or merge efforts if needed.
3) Speaking of which, I think the single-quote method is preferred over symbols going forward: http://acrmp.github.com/foodcritic/#FC001 Would that work for you?
4) Any obection to pinning the xdebug version with an attribute? Just to ensure nothing changes between deploys unless explicitly directed.

Thanks!

**Comment by patcon** [comment]
//cc @walkah

Also, might also add some customizations to allow for this setup more easily:
http://walkah.net/blog/debugging-php-with-vagrant/

**Comment by dkingofpa** [comment]
Disclaimer:  I'm still getting up to speed with Chef best practices.  :)
1.  Wish I did, but I don't.  Needed to get other work done.
2.  I equate the root namespace for cookbook attributes to the actual cookbook.  If `php` is the root, I would look for xdebug.rb  in the php cookbook.  But that's me.  I can see where you're coming from though.  I'm good with using `php` as the attribute root for the cookbook.
3.  Ugh, I'm so confused by opscode's own cookbooks that don't follow a standard when it comes to symbols vs. strings.  I'm new to ruby and had difficulty trying to figure out when I should use each method.  In the end I decided to use symbols (making sure my naming convention didn't use dashes) since it appeared that's what rubyists advocated.  But if opscode is "on the record" saying that the single-quote method is preferred, then I'm fully on board with that.
4.  A version attribute is good.  I hadn't giving it much thought yet.  I was just implementing the latest stable version after seeing the versioning and platform train wreck that is in the php cookbook.
5.  Those are in the xdebug.ini.erb template.  I just didn't implement them yet.  I was planning on doing a 1-to-1 relationship between xdebug properties and cookbook attributes.

Thanks for stopping by Patrick!  I'd definitely welcome and appreciate any of these changes.
